import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from './side-bar/page';

import Navbar from './header';
import { Suspense } from "react";

import MouseEffect from '../app/components/mouse-components/effect';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
      <MouseEffect></MouseEffect>
        <div className="">
          {/* <Navbar/> */}
          {/* <SideBar/> */}
          {children}
        </div>
      </body>
    </html>
  );
}
